version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=alienz200
      - POSTGRES_DB=devops
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app-devops-spring:
    depends_on:
      - postgres
    image: alighnainia191/devops-spring
    restart: on-failure
    ports:
      - 8099:8099
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:postgresql://postgres:5432/devops",
        "spring.datasource.username" : "postgres",
        "spring.datasource.password" : "alienz200",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQL81Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
volumes:
  postgres-data: