version: '3'
services:
  devops-back:
    image: devops-spring
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8099:8099"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/devops
      - SPRING_PROFILES_ACTIVE=prod

  postgres:
    image: postgres:latest
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: devops
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres-data: